"use client";

import { Area, AreaChart, CartesianGrid, ComposedChart, Legend, Line, ReferenceArea, ReferenceLine, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { DemandPoint, ProjectionPoint } from "@/lib/contracts/engine";
import { num } from "./workspace";

const axis = { fontSize: 9, fill: "#8b9897" }; const tooltipStyle = { border: "1px solid #e2e9e0", borderRadius: 9, fontSize: 11, boxShadow: "0 4px 20px #14332910" };
export function DemandChart({ history, unit }: { history: DemandPoint[]; unit: string }) {
  const data = history.map(p => ({ ...p, actual: p.forecast === undefined ? p.raw : null, clean: p.forecast === undefined ? p.cleaned : null, compensated: p.forecast === undefined ? p.adjusted : null, forecast: p.forecast ?? null }));
  const forecastStart = data.find(p => p.forecast !== null)?.month;
  return <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={data} margin={{ top: 15, right: 15, left: -15, bottom: 0 }}><CartesianGrid stroke="#edf1eb" vertical={false}/><XAxis dataKey="month" tick={axis} axisLine={false} tickLine={false} minTickGap={30}/><YAxis tick={axis} axisLine={false} tickLine={false} tickFormatter={v => num(Number(v))}/><Tooltip contentStyle={tooltipStyle} formatter={(v, name) => [`${num(Number(v), 1)} ${unit}`, name]}/><Legend wrapperStyle={{ fontSize: 10, paddingTop: 12 }}/>{data.filter(p => p.lost > 0 && p.forecast === null).map(p => <ReferenceArea key={p.month} x1={p.month} x2={p.month} fill="#eddbad" fillOpacity={.4} stroke="#eddbad" strokeOpacity={.45}/>)}{forecastStart && <ReferenceLine x={forecastStart} stroke="#abc8ae" strokeDasharray="4 4" label={{ value: "Прогноз", position: "insideTopRight", fill: "#79977d", fontSize: 9 }}/>}<Area type="monotone" dataKey="actual" name="Исходные продажи" fill="#dce7e3" fillOpacity={.35} stroke="#a2b9b5" strokeWidth={1.5}/><Line type="monotone" dataKey="clean" name="Без разовых заказов" stroke="#88a8c0" strokeWidth={1.5} dot={false}/><Line type="monotone" dataKey="compensated" name="С компенсацией дефицита" stroke="#22877a" strokeWidth={2} dot={false}/><Line type="monotone" dataKey="forecast" name="Прогноз" stroke="#b48e45" strokeWidth={2.5} strokeDasharray="5 3" dot={false} connectNulls={false}/></ComposedChart></ResponsiveContainer></div>;
}
export function StockChart({ projection, unit }: { projection: ProjectionPoint[]; unit: string }) {
  return <div className="chart-container"><ResponsiveContainer width="100%" height="100%"><ComposedChart data={projection} margin={{ top: 10, right: 15, left: -12, bottom: 0 }}><CartesianGrid stroke="#edf1eb" vertical={false}/><XAxis dataKey="date" tick={axis} axisLine={false} tickLine={false} minTickGap={45} tickFormatter={v => String(v).slice(5)}/><YAxis tick={axis} axisLine={false} tickLine={false}/><Tooltip contentStyle={tooltipStyle} formatter={(v, name) => [`${num(Number(v), 1)} ${unit}`, name]}/><Legend wrapperStyle={{ fontSize: 10, paddingTop: 12 }}/><ReferenceLine y={0} stroke="#c87864" strokeDasharray="4 4"/><Area type="stepAfter" dataKey="stock" name="Прогноз остатка" stroke="#288a7c" fill="#b8d9c5" fillOpacity={.3} strokeWidth={2}/><Line type="stepAfter" dataKey="inbound" name="Поступления по ETA" stroke="#c39c5b" strokeWidth={2} dot={false}/></ComposedChart></ResponsiveContainer></div>;
}
export function TrendChart({ data, series }: { data: Record<string, string | number>[]; series: { key: string; name: string; color: string }[] }) {
  return <div className="chart-container tall"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 15, right: 20, left: 0, bottom: 0 }}><CartesianGrid stroke="#edf1eb" vertical={false}/><XAxis dataKey="month" tick={axis} axisLine={false} tickLine={false} minTickGap={35}/><YAxis tick={axis} axisLine={false} tickLine={false} tickFormatter={v => num(Number(v))}/><Tooltip contentStyle={tooltipStyle} formatter={(v, name) => [num(Number(v), 1), name]}/><Legend wrapperStyle={{ fontSize: 10, paddingTop: 16 }}/>{series.map(s => <Area key={s.key} type="monotone" dataKey={s.key} name={s.name} stroke={s.color} strokeWidth={2} fill={s.color} fillOpacity={.05} connectNulls={false}/>)}</AreaChart></ResponsiveContainer></div>;
}
