"use client";

import Link from "next/link";
import { useState } from "react";
import { ArrowRight, Check, Database, FileSpreadsheet, FlaskConical, FolderUp, ShieldCheck, UploadCloud } from "lucide-react";
import type { DatasetSummary } from "@/lib/contracts/api";
import { api, dateLabel, ErrorNotice, LoadingState, Metric, num, PageHeading, supplierLabel, useWorkspace } from "./workspace";

export function ImportDashboard() {
  const { dataset, details, datasets, loading, refresh, selectDataset } = useWorkspace();
  const [files, setFiles] = useState<File[]>([]); const [name, setName] = useState(""); const [supplier, setSupplier] = useState("");
  const [busy, setBusy] = useState(""); const [error, setError] = useState(""); const [success, setSuccess] = useState(""); const [severity, setSeverity] = useState(""); const [issueLimit, setIssueLimit] = useState(40);
  async function importData(demo: boolean) {
    setBusy(demo ? "demo" : "upload"); setError(""); setSuccess("");
    try {
      let body: string | FormData;
      if (demo) body = JSON.stringify({ source: "demo" });
      else { const form = new FormData(); files.forEach(file => form.append("files", file)); if (name.trim()) form.append("name", name.trim()); if (supplier) form.append("supplier", supplier); body = form; }
      const result = await api<{ dataset: DatasetSummary }>("/api/import", { method: "POST", body });
      await refresh(result.dataset.id); setSuccess(`${result.dataset.name}: данные загружены. Набор выбран для следующих расчётов.`);
    } catch (e) { setError(e instanceof Error ? e.message : "Не удалось загрузить данные"); }
    finally { setBusy(""); }
  }
  const issues = details?.suppliers.flatMap(s => s.issues.map(i => ({ ...i, supplier: i.supplier || s.supplier }))) || [];
  const filteredIssues = issues.filter(i => !severity || i.severity === severity);
  return <>
    <PageHeading eyebrow="Основа точного расчёта" title="Источники данных" description="Загрузите отчёты IEK и Systeme Electric. Проверьте качество до начала планирования."><Link href="/plan" className="button">К плану закупок <ArrowRight size={14}/></Link></PageHeading>
    <ErrorNotice error={error}/>{success && <div className="notice" role="status"><Check size={14} style={{ display: "inline", verticalAlign: "-3px", marginRight: 7 }}/>{success}</div>}
    <div className="two-columns"><section className="card"><header className="card-header"><div><h2>Загрузить отчёты</h2><p>Каждая загрузка создаёт отдельный набор данных.</p></div><span className="badge">XLSX</span></header><div className="card-body"><div className="upload-drop" onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); setFiles(Array.from(e.dataTransfer.files)); }}><UploadCloud size={32}/><h3>Перенесите файлы Excel сюда</h3><p>Продажи, остатки, динамика, кратность, товары в пути и сезонность</p><label className="sr-only" htmlFor="workbook-files">Выберите рабочие книги</label><input id="workbook-files" type="file" accept=".xlsx" multiple onChange={e => setFiles(Array.from(e.target.files || []))}/></div>
    {files.length > 0 && <div className="file-list">{files.map((file, i) => <div className="file-row" key={`${file.name}-${i}`}><FileSpreadsheet size={15}/><span>{file.name}</span><small>{num(file.size / 1024)} КБ</small></div>)}</div>}
    <div className="upload-fields"><label className="field"><span>Название набора</span><input value={name} onChange={e => setName(e.target.value)} placeholder="Например, отчёты за сентябрь"/></label><label className="field"><span>Поставщик</span><select value={supplier} onChange={e => setSupplier(e.target.value)}><option value="">Определить автоматически</option><option value="IEK">IEK</option><option value="SE">Systeme Electric</option></select></label></div><button className="button primary" disabled={!files.length || !!busy} onClick={() => void importData(false)}>{busy === "upload" ? <span className="spinner"/> : <FolderUp size={15}/>} {busy === "upload" ? "Импортируем и проверяем…" : "Загрузить отчёты"}</button><p className="chart-caption">Отсутствующие источники и некорректные строки попадут в аудит. Исходные файлы не публикуются; нормализованные данные сохраняются в выбранном наборе.</p></div></section>
    <section className="card demo-card"><div className="card-body"><div className="demo-symbol"><FlaskConical size={26}/></div><div className="eyebrow">Можно начать без своих файлов</div><h2>Весь сценарий на демонстрационных данных</h2><p>Реалистичные синтетические отчёты двух поставщиков. Тот же импорт и тот же расчёт, что и для рабочих файлов.</p><div className="demo-features"><span>Сезонный спрос</span><span>Разовый крупный заказ</span><span>Периоды дефицита</span><span>Товары в пути</span><span>Кратность заказа</span></div><button className="button dark" disabled={!!busy} onClick={() => void importData(true)}>{busy === "demo" ? <span className="spinner"/> : <Database size={15}/>} {busy === "demo" ? "Готовим демонстрацию…" : "Загрузить демоданные"}<ArrowRight size={14}/></button><p className="chart-caption">Демо создаёт отдельный набор и помечается DEMO. Настоящие товары, клиенты и объёмы партнёра не используются.</p></div></section></div>
    {busy && <LoadingState text="Обрабатываем рабочие книги. Дождитесь завершения перед переходом к расчёту."/>}
    {loading && !details ? <LoadingState/> : details && dataset && <>
    <div className="metrics"><Metric label="Товаров в наборе" value={num(details.suppliers.reduce((n, s) => n + s.productCount, 0))} detail={dataset.synthetic ? "Синтетические товары" : "Точные коды поставщиков"} tone="teal"/><Metric label="Строк операций" value={num(details.suppliers.reduce((n, s) => n + s.transactionCount, 0))} detail="Подробная история продаж"/><Metric label="Исходных файлов" value={num(details.files.length)} detail={`Данные на ${dateLabel(details.cutoffDate)}`}/><Metric label="Замечаний аудита" value={num(issues.length)} detail="Сохранены вместе с источником" tone="orange"/></div>
    <section className="card"><header className="card-header"><div><h2>Покрытие данных</h2><p>{details.name}</p></div><span className="badge teal"><ShieldCheck size={12}/> Происхождение сохранено</span></header><div className="table-scroll"><table><thead><tr><th>Поставщик</th><th>Товаров</th><th>Операций</th><th>Категории</th><th>Замечания</th></tr></thead><tbody>{details.suppliers.map(s => <tr key={s.supplier}><td><strong>{supplierLabel(s.supplier)}</strong></td><td>{num(s.productCount)}</td><td>{num(s.transactionCount)}</td><td>{s.categories.join(", ") || "Не указаны"}</td><td>{num(s.issues.length)}</td></tr>)}</tbody></table></div><details className="card-body"><summary className="subtle-summary">Файлы и распознанные источники · {details.files.length}</summary><div className="table-scroll"><table><thead><tr><th>Файл</th><th>Поставщик</th><th>Тип</th><th>Строк</th><th>Хеш источника</th></tr></thead><tbody>{details.files.map((f, i) => <tr key={`${f.hash}-${i}`}><td>{f.name}</td><td>{supplierLabel(f.supplier)}</td><td>{f.kind}</td><td>{num(f.rows)}</td><td title={f.hash}><code>{f.hash.slice(0, 12)}</code></td></tr>)}</tbody></table></div></details></section>
    <section className="card"><header className="card-header"><div><h2>Аудит импорта</h2><p>Пропуски, дубликаты, несовпадение отчётов и принятые допущения.</p></div><select aria-label="Уровень замечаний" value={severity} onChange={e => { setSeverity(e.target.value); setIssueLimit(40); }}><option value="">Все замечания</option><option value="error">Ошибки</option><option value="warning">Предупреждения</option><option value="info">Информация</option></select></header><div className="table-scroll"><table><thead><tr><th>Уровень</th><th>Замечание</th><th>Источник</th></tr></thead><tbody>{filteredIssues.slice(0, issueLimit).map((issue, i) => <tr key={i}><td><span className={`badge ${issue.severity === "error" ? "danger" : issue.severity === "warning" ? "warning" : ""}`}>{issue.severity === "error" ? "Ошибка" : issue.severity === "warning" ? "Внимание" : "Информация"}</span></td><td className="issue-message"><strong>{supplierLabel(issue.supplier || "")}</strong> · {issue.message}{issue.code && <span className="product-code">{issue.code}</span>}</td><td className="issue-source" title={issue.source?.file}>{issue.source?.file || "Проверка набора"}{issue.source?.sheet && <div>{issue.source.sheet}{issue.source.row ? ` · строка ${issue.source.row}` : ""}</div>}</td></tr>)}{filteredIssues.length === 0 && <tr><td colSpan={3} style={{ textAlign: "center", padding: 25 }}>Замечаний выбранного уровня нет</td></tr>}</tbody></table></div><footer className="card-footer"><span>Показано {Math.min(issueLimit, filteredIssues.length)} из {num(filteredIssues.length)}</span>{issueLimit < filteredIssues.length && <button className="button small" onClick={() => setIssueLimit(n => n + 100)}>Показать ещё</button>}</footer></section>
    </>}
    {datasets.length > 1 && <section className="card"><header className="card-header"><div><h2>Сохранённые наборы</h2><p>Переключение не изменяет ранее созданные расчёты.</p></div></header><div className="table-scroll"><table><thead><tr><th>Название</th><th>Тип</th><th>Дата данных</th><th>Товаров</th><th/></tr></thead><tbody>{datasets.map(d => <tr key={d.id}><td>{d.name}</td><td><span className={`badge ${d.synthetic ? "demo" : "teal"}`}>{d.synthetic ? "Синтетика" : "Загруженные"}</span></td><td>{dateLabel(d.cutoffDate)}</td><td>{num(d.productCount)}</td><td><button className="button small" disabled={d.id === dataset?.id} onClick={() => selectDataset(d.id)}>{d.id === dataset?.id ? "Выбран" : "Открыть"}</button></td></tr>)}</tbody></table></div></section>}
  </>;
}
