"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ArrowDownToLine, ArrowRight, ArrowUpDown, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, FileClock, Filter, Play, RefreshCw, Save, Search, SlidersHorizontal, Sparkles, X } from "lucide-react";
import type { OrderView, RunView } from "@/lib/contracts/api";
import { DEFAULT_POLICY, type Policy, type Recommendation } from "@/lib/contracts/engine";
import { api, Copilot, dateLabel, EmptyState, ErrorNotice, LoadingState, Metric, num, PageHeading, supplierLabel, useWorkspace } from "./workspace";

type RunSummary = { id: string; createdAt: string; baseRunId: string | null };
type AuditEvent = { id: string; createdAt: string; action?: string; type?: string; actor?: string; payload?: unknown; details?: unknown };
const urgencyLabels = { CRITICAL: "Критично", HIGH: "Высокий", NORMAL: "Планово" };
const confidenceLabels = { high: "Высокая", medium: "Средняя", low: "Низкая" };

export function PlanDashboard() {
  const { datasetId, dataset, details, loading: datasetsLoading } = useWorkspace();
  const [runs, setRuns] = useState<RunSummary[]>([]); const [run, setRun] = useState<RunView>();
  const [policy, setPolicy] = useState<Policy>(DEFAULT_POLICY); const [supplier, setSupplier] = useState(""); const [category, setCategory] = useState("");
  const [query, setQuery] = useState(""); const [urgency, setUrgency] = useState(""); const [reviewOnly, setReviewOnly] = useState(false);
  const [sort, setSort] = useState<{ key: "name" | "quantity" | "urgency" | "coverDays"; direction: number }>({ key: "urgency", direction: 1 });
  const [page, setPage] = useState(0); const [edits, setEdits] = useState<Record<string, string>>({}); const [selected, setSelected] = useState<string[]>([]);
  const [busy, setBusy] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  const [approval, setApproval] = useState<{ order: OrderView; keys?: string[] }>(); const [approver, setApprover] = useState(""); const [acknowledged, setAcknowledged] = useState(false);
  const [audit, setAudit] = useState<{ supplier: string; events: AuditEvent[] }>();
  const categories = useMemo(() => [...new Set((details?.suppliers || []).filter(s => !supplier || s.supplier === supplier).flatMap(s => s.categories))].sort(), [details, supplier]);
  const loadRun = useCallback(async (id: string) => {
    setLoading(true); setError("");
    try { const result = await api<{ run: RunView }>(`/api/runs/${encodeURIComponent(id)}`); setRun(result.run); setPolicy(result.run.result.policy); setEdits({}); setSelected([]); setPage(0); localStorage.setItem(`apollon.run.${result.run.datasetId}`, id); }
    catch (e) { setError(e instanceof Error ? e.message : "Не удалось открыть расчёт"); }
    finally { setLoading(false); }
  }, []);
  useEffect(() => {
    if (!datasetId) return;
    let active = true;
    async function load() {
      setRun(undefined); setLoading(true); setError(""); setEdits({}); setSelected([]); setPage(0);
      try { const result = await api<{ runs: RunSummary[] }>(`/api/runs?datasetId=${encodeURIComponent(datasetId)}`); if (!active) return; setRuns(result.runs); const saved = localStorage.getItem(`apollon.run.${datasetId}`); const id = result.runs.find(r => r.id === saved)?.id || result.runs[0]?.id; if (id) { const loaded = await api<{ run: RunView }>(`/api/runs/${encodeURIComponent(id)}`); if (active) { setRun(loaded.run); setPolicy(loaded.run.result.policy); } } }
      catch (e) { if (active) setError(e instanceof Error ? e.message : "Не удалось открыть расчёты"); }
      finally { if (active) setLoading(false); }
    }
    void load(); return () => { active = false; };
  }, [datasetId]);
  function updatePolicy<K extends keyof Policy>(key: K, value: Policy[K]) { setPolicy(p => ({ ...p, [key]: value })); }
  async function calculate(scenario = false) {
    if (!datasetId) return; setBusy("calculate"); setError(""); setSuccess("");
    try {
      const result = await api<{ run: RunView }>("/api/runs", { method: "POST", body: JSON.stringify({ datasetId, policy, ...(supplier ? { supplier } : {}), ...(category ? { category } : {}), ...(scenario && run ? { baseRunId: run.id } : {}) }) });
      setRun(result.run); setRuns(r => [{ id: result.run.id, createdAt: result.run.createdAt, baseRunId: scenario ? run?.id || null : null }, ...r]); setEdits({}); setSelected([]); setPage(0); localStorage.setItem(`apollon.run.${datasetId}`, result.run.id); setSuccess(scenario ? "Сценарий рассчитан. Исходный расчёт сохранён без изменений." : "Расчёт готов. Проверьте рекомендации перед утверждением.");
    } catch (e) { setError(e instanceof Error ? e.message : "Ошибка расчёта"); }
    finally { setBusy(""); }
  }
  const recommendations = useMemo(() => run?.result.recommendations || [], [run]);
  function quantity(r: Recommendation) { return run?.orders.find(o => o.supplier === r.supplier)?.quantities[r.key] ?? r.quantity; }
  const filtered = useMemo(() => {
    const ranks = { CRITICAL: 0, HIGH: 1, NORMAL: 2 };
    return recommendations.filter(r => (!supplier || r.supplier === supplier) && (!category || r.category === category) && (!urgency || r.urgency === urgency) && (!reviewOnly || r.needsReview) && (!query || `${r.name} ${r.code} ${r.supplierArticle}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))).sort((a, b) => {
      if (sort.key === "name") return a.name.localeCompare(b.name, "ru") * sort.direction;
      if (sort.key === "urgency") return (ranks[a.urgency] - ranks[b.urgency]) * sort.direction;
      return ((a[sort.key] ?? Infinity) - (b[sort.key] ?? Infinity)) * sort.direction;
    });
  }, [recommendations, supplier, category, urgency, reviewOnly, query, sort]);
  const pageSize = 20; const pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)); const activePage = Math.min(page, pageCount - 1); const visible = filtered.slice(activePage * pageSize, (activePage + 1) * pageSize);
  function toggleSort(key: typeof sort.key) { setSort(s => ({ key, direction: s.key === key ? -s.direction : 1 })); }
  function toggleKey(key: string) { setSelected(s => s.includes(key) ? s.filter(k => k !== key) : [...s, key]); }
  function updateOrder(order: OrderView) { setRun(r => r ? { ...r, orders: r.orders.map(o => o.id === order.id ? order : o) } : r); }
  async function saveEdits(order: OrderView) {
    const orderEdits = Object.entries(edits).filter(([key]) => key in order.quantities).map(([key, value]) => ({ key, quantity: Number(value) }));
    if (orderEdits.some(e => !Number.isFinite(e.quantity) || e.quantity < 0 || edits[e.key].trim() === "")) { setError("Количество должно быть неотрицательным числом."); return; }
    setBusy(order.id); setError(""); setSuccess("");
    try { const result = await api<{ order: OrderView }>(`/api/orders/${order.id}`, { method: "PATCH", body: JSON.stringify({ expectedRevision: order.revision, edits: orderEdits }) }); updateOrder(result.order); setEdits(current => Object.fromEntries(Object.entries(current).filter(([key]) => !(key in order.quantities)))); setSuccess("Изменения сохранены. Для экспорта необходимо заново утвердить заказ."); }
    catch (e) { setError(e instanceof Error ? e.message : "Не удалось сохранить"); } finally { setBusy(""); }
  }
  async function approve() {
    if (!approval) return; setBusy("approve"); setError("");
    try { const result = await api<{ order: OrderView }>(`/api/orders/${approval.order.id}/approve`, { method: "POST", body: JSON.stringify({ expectedRevision: approval.order.revision, approver, acknowledgedEstimates: acknowledged, keys: approval.keys }) }); updateOrder(result.order); setApproval(undefined); setSelected([]); setSuccess(`Заказ ${supplierLabel(result.order.supplier)} утверждён. Версия ${result.order.revision} зафиксирована для экспорта.`); }
    catch (e) { setError(e instanceof Error ? e.message : "Не удалось утвердить"); } finally { setBusy(""); }
  }
  async function download(order: OrderView, format: string) {
    setBusy(`export-${order.id}`); setError("");
    try { const response = await fetch(`/api/export?orderId=${order.id}&revision=${order.revision}&format=${format}`); if (!response.ok) { const result = await response.json(); throw new Error(result.error || "Ошибка экспорта"); } const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `Apollon-${order.supplier}-v${order.revision}.${format === "email" ? "txt" : format}`; anchor.click(); URL.revokeObjectURL(url); }
    catch (e) { setError(e instanceof Error ? e.message : "Ошибка экспорта"); } finally { setBusy(""); }
  }
  async function showAudit(order: OrderView) { setError(""); try { const result = await api<{ events: AuditEvent[] }>(`/api/orders/${order.id}`); setAudit({ supplier: order.supplier, events: result.events }); } catch (e) { setError(e instanceof Error ? e.message : "Ошибка истории"); } }
  const approvedCount = run?.orders.reduce((n, o) => n + o.approvedKeys.length, 0) || 0;
  if (datasetsLoading) return <LoadingState/>;
  return <>
    <PageHeading eyebrow="Планирование пополнения" title="План закупок" description="Рассчитайте потребность. Проверьте обоснование. Утвердите уверенно."><Link href="/import" className="button"><ArrowDownToLine size={15}/> Источники данных</Link><button className="button primary" disabled={!datasetId || !!busy || loading} onClick={() => void calculate()}>{busy === "calculate" ? <span className="spinner"/> : <Play size={14}/>} Рассчитать заказ</button></PageHeading>
    <ErrorNotice error={error}/>{success && <div className="notice" role="status">{success}</div>}
    {!datasetId ? <EmptyState/> : <>
      <div className="metrics"><Metric label="Позиций в расчёте" value={run ? num(recommendations.length) : "—"} detail={run ? `${new Set(recommendations.map(r => r.supplier)).size} поставщика · ${dateLabel(run.result.cutoffDate)}` : `${num(dataset?.productCount)} товаров в наборе`} tone="teal"/><Metric label="Требуют заказа" value={run ? num(recommendations.filter(r => quantity(r) > 0).length) : "—"} detail="Потребность после учёта остатков"/><Metric label="Риск дефицита" value={run ? num(recommendations.filter(r => r.urgency === "CRITICAL").length) : "—"} detail="Дефицит до следующей поставки" tone="red"/><Metric label="Утверждено позиций" value={run ? num(approvedCount) : "—"} detail={approvedCount ? "Зафиксированы для экспорта" : "Ожидают проверки менеджера"} tone="orange"/></div>
      <section className="card"><header className="card-header"><div><h2><SlidersHorizontal size={16} style={{ display: "inline", verticalAlign: "-3px", marginRight: 8 }}/> Параметры планирования</h2><p>Настройки применяются к новому расчёту. Существующие версии сохраняются.</p></div><span className="badge teal">Горизонт {policy.leadTimeDays + policy.reviewDays} дней</span></header><div className="card-body"><div className="policy-grid">
        <label className="field"><span>Поставщик</span><select value={supplier} onChange={e => { setSupplier(e.target.value); setCategory(""); setPage(0); }}><option value="">Все поставщики</option>{(details?.suppliers || []).map(s => <option key={s.supplier} value={s.supplier}>{supplierLabel(s.supplier)}</option>)}</select></label>
        <label className="field"><span>Категория</span><select value={category} onChange={e => { setCategory(e.target.value); setPage(0); }}><option value="">Все категории</option>{categories.map(c => <option key={c} value={c}>{c || "Без категории"}</option>)}</select></label>
        <label className="field"><span>Срок поставки, дней</span><input type="number" min={1} max={365} value={policy.leadTimeDays} onChange={e => updatePolicy("leadTimeDays", Number(e.target.value))}/></label>
        <label className="field"><span>Период обзора, дней</span><input type="number" min={1} max={180} value={policy.reviewDays} onChange={e => updatePolicy("reviewDays", Number(e.target.value))}/></label>
        <label className="field"><span>Уровень сервиса, %</span><input type="number" min={50} max={99.9} step={.1} value={Number((policy.serviceLevel * 100).toFixed(2))} onChange={e => updatePolicy("serviceLevel", Number(e.target.value) / 100)}/></label>
        <label className="field"><span>Рост спроса, % / год</span><input type="number" min={-95} max={300} placeholder="Из данных" value={policy.growthRate === null ? "" : Number((policy.growthRate * 100).toFixed(2))} onChange={e => updatePolicy("growthRate", e.target.value === "" ? null : Number(e.target.value) / 100)}/></label>
      </div><div className="policy-toggles"><label className="checkbox-label"><input type="checkbox" checked={policy.stockoutCompensation} onChange={e => updatePolicy("stockoutCompensation", e.target.checked)}/> Компенсация упущенного спроса</label><label className="checkbox-label"><input type="checkbox" checked={policy.outlierFiltering} onChange={e => updatePolicy("outlierFiltering", e.target.checked)}/> Исключение разовых заказов</label><div className="policy-actions"><button className="button small" disabled={!run || !!busy} onClick={() => void calculate(true)}><Sparkles size={13}/> Сравнить сценарий</button></div></div>
      <details className="advanced-policy"><summary className="subtle-summary">Расширенные настройки и политики категорий <ChevronDown size={12} style={{ display: "inline" }}/></summary><div className="inline-controls"><label className="field"><span>Минимальный запас, дней</span><input type="number" min={0} max={180} value={policy.safetyDays} onChange={e => updatePolicy("safetyDays", Number(e.target.value))}/></label><label className="field"><span>Как применять рост</span><select value={policy.growthMode} onChange={e => updatePolicy("growthMode", e.target.value as Policy["growthMode"])}><option value="replace">Заменить оценённый тренд</option><option value="additive">Добавить к тренду</option></select></label></div><p className="chart-caption">Значения категорий — редактируемые предположения. Их бизнес-смысл не указан в исходных отчётах. Политика категории имеет приоритет над общей.</p><div className="category-policy-grid">{categories.map(c => <div className="field" key={c}><span>Категория {c || "без категории"}</span><label className="field"><span>Уровень сервиса, %</span><input type="number" min={50} max={99.9} step={.1} aria-label={`Сервис категории ${c}`} value={Number(((policy.categoryServiceLevels[c] ?? policy.serviceLevel) * 100).toFixed(2))} onChange={e => updatePolicy("categoryServiceLevels", { ...policy.categoryServiceLevels, [c]: Number(e.target.value) / 100 })}/></label><label className="field"><span>Минимальный запас, дней</span><input type="number" min={0} max={180} aria-label={`Запас категории ${c}`} value={policy.categorySafetyDays[c] ?? policy.safetyDays} onChange={e => updatePolicy("categorySafetyDays", { ...policy.categorySafetyDays, [c]: Number(e.target.value) })}/></label></div>)}</div></details>
      </div></section>
      {loading ? <LoadingState text="Открываем сохранённый расчёт…"/> : !run ? <div className="empty-state"><div className="empty-icon"><Play size={25}/></div><h2>Данные готовы к расчёту</h2><p>Задайте параметры выше. Apollon учтёт историю спроса, остатки, сезонность и ожидаемые поставки.</p><button className="button primary" disabled={!!busy} onClick={() => void calculate()}>Рассчитать первый заказ <ArrowRight size={15}/></button></div> : <>
      {run.result.warnings.length > 0 && <details className="notice warning"><summary>Допущения расчёта · {run.result.warnings.length}</summary>{run.result.warnings.map((w, i) => <p key={i}>{w}</p>)}</details>}
      {run.scenarioDelta && <details className="scenario-banner" open><summary>Сценарий: изменилось {run.scenarioDelta.filter(d => d.delta !== 0).length} позиций. Базовый расчёт сохранён.</summary><div className="scenario-table"><table><thead><tr><th>Позиция</th><th>Было</th><th>Стало</th><th>Изменение</th></tr></thead><tbody>{run.scenarioDelta.filter(d => d.delta !== 0).slice(0, 100).map(d => <tr key={d.key}><td>{d.key}</td><td>{num(d.before)}</td><td>{num(d.after)}</td><td>{d.delta > 0 ? "+" : ""}{num(d.delta)}</td></tr>)}</tbody></table></div></details>}
      <section className="card"><header className="card-header"><div><h2>Рекомендации к заказу <span className="badge" style={{ marginLeft: 8 }}>{num(filtered.length)}</span></h2><p>Количество можно изменить. Любое изменение снимает утверждение.</p></div><div className="inline-controls"><label className="sr-only" htmlFor="run-select">Сохранённый расчёт</label><select id="run-select" value={run.id} onChange={e => void loadRun(e.target.value)} style={{ fontSize: 10, maxWidth: 230 }} disabled={!!busy}>{runs.map(r => <option key={r.id} value={r.id}>{dateLabel(r.createdAt)} · {new Date(r.createdAt).toLocaleTimeString("ru-RU", { hour: "2-digit", minute: "2-digit" })}{r.baseRunId ? " · сценарий" : ""}</option>)}</select><button className="icon-button" aria-label="Обновить расчёт" onClick={() => void loadRun(run.id)} disabled={!!busy}><RefreshCw size={15}/></button></div></header>
      <div className="filters"><div className="search-field"><Search size={15}/><input aria-label="Поиск по товарам" placeholder="Название, артикул или код…" value={query} onChange={e => { setQuery(e.target.value); setPage(0); }}/></div><Filter size={14} color="#8b999a"/><select aria-label="Фильтр срочности" value={urgency} onChange={e => { setUrgency(e.target.value); setPage(0); }}><option value="">Любая срочность</option><option value="CRITICAL">Критично</option><option value="HIGH">Высокий приоритет</option><option value="NORMAL">Планово</option></select><label className="checkbox-label"><input type="checkbox" checked={reviewOnly} onChange={e => { setReviewOnly(e.target.checked); setPage(0); }}/> Требуют проверки</label><span className="filter-spacer"/><span className="muted" style={{ fontSize: 10 }}>{selected.length ? `Выбрано: ${selected.length}` : "Группировка по поставщику"}</span></div>
      <div className="table-scroll"><table><thead><tr><th><input type="checkbox" aria-label="Выбрать все позиции на странице" checked={visible.length > 0 && visible.every(r => selected.includes(r.key))} onChange={e => setSelected(current => e.target.checked ? [...new Set([...current, ...visible.map(r => r.key)])] : current.filter(k => !visible.some(r => r.key === k)))}/></th><th><button className="table-heading-button" onClick={() => toggleSort("name")}>Наименование / артикул <ArrowUpDown size={11}/></button></th><th className="number">Остаток</th><th className="number">В пути</th><th className="number"><button className="table-heading-button" onClick={() => toggleSort("coverDays")}>Запас, дн. <ArrowUpDown size={11}/></button></th><th><button className="table-heading-button" onClick={() => toggleSort("quantity")}>К заказу <ArrowUpDown size={11}/></button></th><th><button className="table-heading-button" onClick={() => toggleSort("urgency")}>Приоритет <ArrowUpDown size={11}/></button></th><th>Уверенность</th><th/></tr></thead>
      <tbody>{[...new Set(visible.map(r => r.supplier))].map(s => { const order = run.orders.find(o => o.supplier === s); const rows = visible.filter(r => r.supplier === s); const dirty = order && Object.keys(edits).some(k => k in order.quantities); const selectedKeys = selected.filter(k => recommendations.find(r => r.key === k)?.supplier === s); return <SupplierRows key={s} supplier={s} count={filtered.filter(r => r.supplier === s).length} order={order} dirty={!!dirty} busy={!!busy} onSave={() => order && void saveEdits(order)} onApprove={() => { if (order) { setApproval({ order, keys: selectedKeys.length ? selectedKeys : undefined }); setAcknowledged(false); setError(""); } }} onAudit={() => order && void showAudit(order)} onDownload={format => order && void download(order, format)} selectedCount={selectedKeys.length}>{rows.map(r => <tr key={r.key}><td><input type="checkbox" aria-label={`Выбрать ${r.code}`} checked={selected.includes(r.key)} onChange={() => toggleKey(r.key)}/></td><td><Link className="product-name" href={`/plan/${run.id}/sku/${encodeURIComponent(r.key)}`}>{r.name}</Link><span className="product-code">{r.supplierArticle || r.code} · {r.unit} <span className="badge" style={{ fontSize: 8, padding: "1px 4px", marginLeft: 4 }}>{r.abc}{r.xyz}</span>{r.needsReview && <span title="Требует проверки" style={{ color: "#b38f4d", marginLeft: 5 }}>●</span>}</span></td><td className="number">{num(r.provenance.availableStock, 1)}{r.provenance.stockKind !== "current" && <span className="product-code">оценка</span>}</td><td className="number">{num(r.provenance.eligibleInbound, 1)}</td><td className="number">{num(r.coverDays, 1)}</td><td><input type="number" min={0} step="any" aria-label={`Количество ${r.code}`} className={`quantity-input ${r.key in edits ? "edited" : ""}`} value={edits[r.key] ?? quantity(r)} onChange={e => setEdits(current => ({ ...current, [r.key]: e.target.value }))}/><span className="unit-label">{r.unit}</span>{order?.approvedKeys.includes(r.key) && <Check size={12} color="#4f9272" style={{ display: "inline", marginLeft: 4 }}/>}</td><td><span className={`badge ${r.urgency}`}>{urgencyLabels[r.urgency]}</span></td><td><span className={`badge ${r.confidence}-confidence`}>{confidenceLabels[r.confidence]}</span></td><td><Link className="icon-button" aria-label={`Обоснование ${r.code}`} href={`/plan/${run.id}/sku/${encodeURIComponent(r.key)}`}><ArrowRight size={14}/></Link></td></tr>)}</SupplierRows>; })}{visible.length === 0 && <tr><td colSpan={9} style={{ textAlign: "center", padding: 35, color: "#86938b" }}>Нет позиций по выбранным условиям</td></tr>}</tbody></table></div>
      <footer className="card-footer"><span>{filtered.length ? `${activePage * pageSize + 1}–${Math.min((activePage + 1) * pageSize, filtered.length)}` : "0"} из {num(filtered.length)} позиций · {Object.keys(edits).length ? <span className="save-hint">Есть несохранённые изменения</span> : "Данные расчёта сохранены"}</span><div className="pager"><button aria-label="Предыдущая страница" disabled={activePage === 0} onClick={() => setPage(p => p - 1)}><ChevronLeft size={13}/></button><span>{activePage + 1} / {pageCount}</span><button aria-label="Следующая страница" disabled={activePage >= pageCount - 1} onClick={() => setPage(p => p + 1)}><ChevronRight size={13}/></button></div></footer></section>
      <div className="notice"><CheckCheck size={15} style={{ display: "inline", verticalAlign: "-3px", marginRight: 7 }}/> Каждый заказ проходит вашу проверку. Экспортируется только зафиксированная утверждённая версия; автоматической отправки поставщику нет.</div>
      </>}
    </>}
    <Copilot runId={run?.id}/>
    {approval && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="approve-title"><header><h2 id="approve-title">Утверждение заказа</h2><button className="icon-button" aria-label="Закрыть" onClick={() => setApproval(undefined)} disabled={busy === "approve"}><X size={18}/></button></header><div className="modal-body"><p>Проверьте допущения и подтвердите количество. Утверждённые данные будут зафиксированы для экспорта.</p><ErrorNotice error={error}/><div className="approval-summary"><strong>{supplierLabel(approval.order.supplier)}</strong> · версия {approval.order.revision}<br/>{approval.keys ? `${approval.keys.length} выбранных позиций` : "Все позиции поставщика"}</div><label className="field"><span>Ответственный сотрудник</span><input placeholder="Имя и фамилия" value={approver} onChange={e => setApprover(e.target.value)} autoFocus/></label><label className="checkbox-label"><input type="checkbox" checked={acknowledged} onChange={e => setAcknowledged(e.target.checked)}/> Я проверил расчёт, оценки остатков и предупреждения</label><p className="chart-caption">В демонстрации имя записывается в историю без проверки личности.</p></div><footer><button className="button" onClick={() => setApproval(undefined)} disabled={busy === "approve"}>Отмена</button><button className="button primary" disabled={!!busy || approver.trim().length < 2 || !acknowledged} onClick={() => void approve()}>{busy === "approve" ? "Утверждаем…" : "Утвердить заказ"}<Check size={14}/></button></footer></section></div>}
    {audit && <div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="audit-title"><header><h2 id="audit-title">История · {supplierLabel(audit.supplier)}</h2><button className="icon-button" aria-label="Закрыть историю" onClick={() => setAudit(undefined)}><X size={18}/></button></header><div className="modal-body">{audit.events.length ? audit.events.map(e => <div className="audit-row" key={e.id}><FileClock size={16}/><div><strong>{e.action || e.type || "Изменение"}</strong>{e.actor && <p>{e.actor}</p>}<pre>{JSON.stringify(e.payload || e.details || {}, null, 2)}</pre><small>{new Date(e.createdAt).toLocaleString("ru-RU")}</small></div></div>) : <p>Событий пока нет.</p>}</div></section></div>}
  </>;
}

function SupplierRows({ supplier, count, order, dirty, busy, onSave, onApprove, onAudit, onDownload, selectedCount, children }: { supplier: string; count: number; order?: OrderView; dirty: boolean; busy: boolean; onSave: () => void; onApprove: () => void; onAudit: () => void; onDownload: (format: string) => void; selectedCount: number; children: React.ReactNode }) {
  return <><tr className="supplier-row"><td colSpan={9}><div className="supplier-heading"><span className={`supplier-logo ${supplier}`}>{supplier === "SE" ? "systeme" : "IEK"}</span><strong>{supplierLabel(supplier)}</strong><small>{num(count)} позиций</small>{order && <span className={`badge ${order.status}`}>{order.status === "APPROVED" ? "Утверждён" : "Черновик"} · v{order.revision}</span>}<div className="supplier-actions">{dirty && <button className="button small" onClick={onSave} disabled={busy}><Save size={12}/> Сохранить</button>}<button className="icon-button" title="История изменений" aria-label={`История ${supplier}`} onClick={onAudit}><FileClock size={15}/></button><button className="button small" onClick={onApprove} disabled={busy || dirty || !order}><Check size={12}/>{selectedCount ? `Утвердить ${selectedCount}` : "Утвердить"}</button>{order?.status === "APPROVED" && <><button className="button small" onClick={() => onDownload("xlsx")} disabled={busy || dirty}><ArrowDownToLine size={12}/> XLSX</button><button className="button small" onClick={() => onDownload("csv")} disabled={busy || dirty}>CSV</button><button className="button small" onClick={() => onDownload("email")} disabled={busy || dirty}>Письмо</button></>}</div></div></td></tr>{children}</>;
}
